<a href="https://colab.research.google.com/github/ritaromeroruiz23/practicaGit/blob/main/Proyecto2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [4]:
df=pd.read_csv('/content/kiva_loans.csv')
pd.read_csv('/content/kiva_loans.csv')

,id,funded_amount,loan_amount,activity,sector,use,country_code,country,region,currency,partner_id,posted_time,disbursed_time,funded_time,term_in_months,lender_count,tags,borrower_genders,repayment_interval,date
0,653051,300.0,300.0,Fruits & Vegetables,Food,"To buy seasonal, fresh fruits to sell.",PK,Pakistan,Lahore,PKR,247.0,2014-01-01 06:12:39+00:00,2013-12-17 08:00:00+00:00,2014-01-02 10:06:32+00:00,12.0,12.0,NaN,female,irregular,2014-01-01
1,653053,575.0,575.0,Rickshaw,Transportation,to repair and maintain the auto rickshaw used ...,PK,Pakistan,Lahore,PKR,247.0,2014-01-01 06:51:08+00:00,2013-12-17 08:00:00+00:00,2014-01-02 09:17:23+00:00,11.0,14.0,NaN,"female, female",irregular,2014-01-01
2,653068,150.0,150.0,Transportation,Transportation,To repair their old cycle-van and buy another ...,IN,India,Maynaguri,INR,334.0,2014-01-01 09:58:07+00:00,2013-12-17 08:00:00+00:00,2014-01-01 16:01:36+00:00,43.0,6.0,"user_favorite, user_favorite",female,bullet,2014-01-01
3,653063,200.0,200.0,Embroidery,Arts,to purchase an embroidery machine and a variet...,PK,Pakistan,Lahore,PKR,247.0,2014-01-01 08:03:11+00:00,2013-12-24 08:00:00+00:00,2014-01-01 13:00:00+00:00,11.0,8.0,NaN,female,irregular,2014-01-01
4,653084,400.0,400.0,Milk Sales,Food,to purchase one buffalo.,PK,Pakistan,Abdul Hakeem,PKR,245.0,2014-01-01 11:53:19+00:00,2013-12-17 08:00:00+00:00,2014-01-01 19:18:51+00:00,14.0,16.0,NaN,female,monthly,2014-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
643377,1305379,525.0,525.0,Livestock,Agriculture,to buy feed and other supplies to raise her li...,PH,Philippines,"Guihulngan, Negros Oriental",PHP,145.0,2017-05-24 08:07:42+00:00,2017-05-03 07:00:00+00:00,2017-05-31 04:25:21+00:00,7.0,1.0,NaN,female,irregular,2017-05-24
643378,1305330,225.0,225.0,General Store,Retail,to buy additional stocks of groceries to sell.,PH,Philippines,"Pulupandan, Negros Occidental",PHP,145.0,2017-05-24 07:39:37+00:00,2017-05-12 07:00:00+00:00,2017-05-30 23:21:04+00:00,8.0,1.0,NaN,female,irregular,2017-05-24
643379,1305133,250.0,250.0,Pigs,Agriculture,"to buy sacks of feed, additional piglets, and ...",PH,Philippines,"Culasi, Antique",PHP,145.0,2017-05-24 06:10:56+00:00,2017-05-11 07:00:00+00:00,2017-06-01 23:57:35+00:00,13.0,7.0,"#Repeat Borrower, #Animals, #Woman Owned Biz",female,irregular,2017-05-24
643380,1305535,525.0,525.0,General Store,Retail,to buy additional stock of groceries to sell.,PH,Philippines,"La Castellana, Negros Occidental",PHP,145.0,2017-05-24 09:30:19+00:00,2017-05-17 07:00:00+00:00,2017-05-31 13:51:13+00:00,8.0,1.0,NaN,female,irregular,2017-05-24
643381,1304843,125.0,125.0,Fishing,Food,to cover the cost of fishing boat repair,PH,Philippines,"Puntod, Lopez Jaena, Misamis Occidental",PHP,136.0,2017-05-24 01:42:26+00:00,2017-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 581654 entries, 0 to 581653
Data columns (total 20 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id                  581654 non-null  int64
 1   funded_amount       581654 non-null  float64
 2   loan_amount         581654 non-null  float64
 3   activity            581654 non-null  object
 4   sector              581654 non-null  object
 5   use                 577501 non-null  object
 6   country_code        581645 non-null  object
 7   country             581653 non-null  object
 8   region              529374 non-null  object
 9   currency            581653 non-null  object
 10  partner_id          569072 non-null  float64
 11  posted_time         581653 non-null  object
 12  disbursed_time      579704 non-null  object
 13  funded_time         542436 non-null  object
 14  term_in_months      581653 non-null  float64
 15  lender_count        581653 non-null  float64
 16  tags                422157 non-null  object
 17  borrower_genders    577512 non-null  object
 18  repayment_interval  581653 non-null  object
 19  date                581653 non-null  object
dtypes: float64(5), int64(1), object(14)
memory usage: 88.8+ MB

In [8]:
df.shape

(581654, 20)

In [9]:
df.count()

id                    581654
funded_amount         581654
loan_amount           581654
activity              581654
sector                581654
use                   577501
country_code          581645
country               581653
region                529374
currency              581653
partner_id            569072
posted_time           581653
disbursed_time        579704
funded_time           542436
term_in_months        581653
lender_count          581653
tags                  422157
borrower_genders      577512
repayment_interval    581653
date                  581653
dtype: int64